{
 "title": "Mini Log Analytics API Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "Total API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Error Rate (500s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_errors_total{status_code=\"500\"}[1m]))",
     "legendFormat": "Errors/sec"
    }
   ]
  },
  {
   "title": "Request Latency (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, endpoint))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}